# A sample Gemfile
source "http://rubygems.org"
gem "rspec", "= 1.3.0"
gem "rails", "= 2.3.6"
gem "factory_girl"  
gem "rspec-rails", "= 1.3.2"
gem "webrat", "= 0.7.1"
gem "gherkin", "=2.2.9"
gem "diff-lcs"
gem "cucumber-rails", "= 0.3.2"
gem "database_cleaner", "= 0.5.0"